import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SideBar from "@/components/ui/SideBar";
import TopNavBar from "@/components/ui/TopNavBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={``}>
        <div className="flex">
          <SideBar />
           <main className="flex-1">
              <TopNavBar />
              <div className="flex flex-col  sm:border-r sm:border-slate-50 min-h-screen">
               {children}
              </div>
           </main>
        </div>
        
      </body>
    </html>
  );
}
